name: 'DigitalOcean App Deployment Action'
description: 'GitHub Action for Creating an App Deployment via DigitalOcean API.'
author: 'rdarida'

branding:
  icon: 'upload'
  color: 'gray-dark'

inputs:
  digitalocean-token:
    description: 'Read and write token for DigitalOcean API'
    required: true

  digitalocean-appid:
    description: 'ID of the DigitalOcean App'
    required: true

runs:
  using: 'composite'
  steps:
    - run: >-
        curl
        -X POST
        -H "Content-Type: application/json"
        -H "Authorization: Bearer ${{ inputs.digitalocean-token }}"
        "https://api.digitalocean.com/v2/apps/${{ secrets.digitalocean-appid }}/deployments"
      shell: bash
